---
- hosts: web
  gather_facts: yes
  become: yes
  tasks:
    - name: stop the nginx service
      service:
        name: nginx
        state: stopped
    - name: Ensure nginx is uninstalled
      package:
        name: nginx
        state: absent
    - name: remove config file soft linke
      file:
        path: /etc/nginx/sites-enabled/default 
        state: absent
    - name: remove config file
      file:
        path: /etc/nginx/sites-available/static_site.cfg
        state: absent
    - name: remove directory structure
      file:
        path: /etc/nginx/custom_sites/
        state: absent



  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted


